# This is a TOML document. Boom.

title = "TOML for GAgg"

[owner]
name = "Adrian Jackson"
organization = "Devops Consulting Ltd"
bio = "Saving Drudge."
dob = 1964-06-02T11:30:00Z # Auspicious day.

[agg]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
messageSend = false

[debug]
enabled = true


[servers]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ] # just an update to make sure parsers support it

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]